_target_: src.tasks.supervised.vlm.captioning_task.CaptioningTask

model:
  name: blip2
  pretrained: true
  model_path: Salesforce/blip2-opt-2.7b
  freeze_vision: false
  freeze_language: false

loss:
  name: cross_entropy
  label_smoothing: 0.1

optimizer:
  name: adamw
  lr: 1e-5
  weight_decay: 0.01
  betas: [0.9, 0.999]

scheduler:
  name: cosine
  warmup_steps: 1000
  min_lr: 1e-6

metrics:
  - bleu
  - meteor
  - cider
  - rouge