# This file is "conf/callbacks/default.yaml"
# It's the 'default' config for the 'callbacks' group.

# This defines a list of callbacks to instantiate

- _target_: pytorch_lightning.callbacks.ModelCheckpoint
  # Save the best model based on validation loss
  dirpath: "${hydra.run.dir}/checkpoints"
  filename: "best-model-{epoch:02d}-{val_loss:.2f}"
  monitor: "val_loss"
  mode: "min"
  save_top_k: 1
  save_last: true

- _target_: pytorch_lightning.callbacks.LearningRateMonitor
  # Log the learning rate
  logging_interval: "step"

- _target_: pytorch_lightning.callbacks.RichProgressBar
  # Just a nice-looking progress bar

