# This file is "conf/trainer/default.yaml"
# It's the 'default' config for the 'trainer' group.

# This tells Hydra to import and use the PyTorch Lightning Trainer class
_target_: pytorch_lightning.Trainer

# These are the arguments to pass to the Trainer's __init__
max_epochs: 10
log_every_n_steps: 50
accelerator: "auto"
devices: "auto"
precision: "16-mixed" # Use '32' or '16-mixed'

